import type { Metadata } from "next";
import Link from "next/link";
import { TxtToSrtConverter } from "./converter";
import { VibeBackgroundGlow } from "@/components/ui/vibe-background-glow";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { JsonLd, toolPageJsonLd } from "@/components/seo/json-ld";

export const metadata: Metadata = {
  title: "Free TXT to SRT Converter Online — Turn Plain Text into Subtitles",
  description:
    "Convert plain text files to SRT subtitle format with auto-generated timestamps. Paste or upload your script and get a ready-to-use .srt file instantly. No upload — 100% private and free.",
  keywords: ["txt to srt", "text to srt", "convert text to srt", "plain text to subtitle", "create srt from text", "txt to srt online", "text to srt converter"],
  alternates: { canonical: "/tools/txt-to-srt" },
};

const jsonLdData = toolPageJsonLd({
  name: "TXT to SRT Converter",
  description: "Convert plain text files to SRT subtitle format with auto-generated timestamps. Free, browser-based, no upload needed.",
  url: "/tools/txt-to-srt",
  faqs: [
    { question: "How are the timestamps generated when converting TXT to SRT?", answer: "Each non-empty line receives 3 seconds of display time with a 0.5-second gap between entries. Timestamps start at 00:00:00,000 and increment sequentially. This default assumes roughly 15 words per subtitle line at a comfortable reading speed." },
    { question: "Can I adjust the timing after converting text to SRT?", answer: "Yes. After converting your TXT to SRT, you can use our Subtitle Shifter tool to offset all timestamps forward or backward. For per-line adjustments, import the SRT into a subtitle editor or video editing software." },
    { question: "What happens to blank lines in my text file?", answer: "Blank lines in the source TXT file are skipped during conversion to SRT. Only non-empty lines become subtitle entries. This means you can use blank lines to organize your script without affecting the output." },
    { question: "Is my file uploaded to a server?", answer: "No. All TXT to SRT conversion happens in your browser using JavaScript. Your text file never leaves your device, making this the most private text to SRT converter available." },
    { question: "Does the TXT to SRT converter support non-English text?", answer: "Yes. The converter handles UTF-8 encoded text, supporting all languages including Chinese, Japanese, Korean, Arabic, Hebrew, Cyrillic, and all European languages." },
    { question: "Which video editors accept SRT files generated from TXT?", answer: "All major video editing software accepts SRT files, including Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro, CapCut, and iMovie. The SRT files generated by our TXT to SRT converter follow the standard SRT specification." },
    { question: "Can I convert song lyrics from TXT to SRT for a music video?", answer: "Yes. Converting lyrics from TXT to SRT is one of the most common use cases. Each line of your lyrics becomes a subtitle entry with 3-second timing. You may want to adjust timing afterward to sync with the actual song tempo." },
  ],
});

const relatedTools = [
  { name: "ASS to SRT", href: "/tools/ass-to-srt" },
  { name: "VTT to SRT", href: "/tools/vtt-to-srt" },
  { name: "SRT to VTT", href: "/tools/srt-to-vtt" },
  { name: "SRT to TXT", href: "/tools/srt-to-txt" },
  { name: "Subtitle Shifter", href: "/tools/subtitle-shifter" },
];

export default function TxtToSrtPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6">
      {jsonLdData.map((data, i) => <JsonLd key={i} data={data} />)}

      {/* ===== Zone 1: Tool (Hero) ===== */}
      <section className="relative py-10 md:py-14">
        <VibeBackgroundGlow />
        <h1 className="relative text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight text-center">
          Convert TXT to SRT — Turn Plain Text into Subtitles
        </h1>
        <p className="relative mt-3 text-center text-muted-foreground max-w-2xl mx-auto">
          Use this free online TXT to SRT converter to transform plain text scripts, transcripts, or lyrics into
          properly formatted SRT subtitle files with auto-generated timestamps. Unlike other subtitle converters
          that transform between existing formats, the text to SRT tool creates timing information from scratch
          because TXT files contain no timestamps at all. Each non-empty line becomes one subtitle entry with a
          3-second default duration. Your file is processed entirely in your browser — nothing is uploaded to any server.
        </p>
        <div className="mt-8"><TxtToSrtConverter /></div>
        <div className="mt-6 rounded-lg bg-muted/40 p-4 text-sm text-muted-foreground">
          <span className="font-medium text-foreground">Need to extract text from subtitles?</span>{" "}
          Try our{" "}
          <Link href="/tools/srt-to-txt" className="font-medium underline underline-offset-4 hover:text-foreground/70">SRT to TXT extractor</Link>{" "}
          to strip timestamps and get plain text from any SRT file.
        </div>
      </section>

      {/* ===== Zone 2: Landing Page Content ===== */}
      <section className="pb-12 border-t pt-10">
        <h2 className="text-2xl font-bold mb-6">How to Convert TXT to SRT in 3 Steps</h2>
        <ol className="grid gap-4 md:grid-cols-3 mb-8">
          <li className="rounded-lg border bg-card p-5">
            <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-foreground text-background text-sm font-bold mb-3">1</span>
            <h3 className="font-semibold mb-1">Upload or Paste Your Text</h3>
            <p className="text-sm text-muted-foreground">
              Drag and drop your .txt file into the TXT to SRT converter above, or paste your text content directly
              into the input area. The converter accepts any plain text — transcripts, scripts, dialogue lists, or
              song lyrics. Each non-empty line will become a separate subtitle entry in the output SRT file.
            </p>
          </li>
          <li className="rounded-lg border bg-card p-5">
            <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-foreground text-background text-sm font-bold mb-3">2</span>
            <h3 className="font-semibold mb-1">Automatic Text to SRT Conversion</h3>
            <p className="text-sm text-muted-foreground">
              The TXT to SRT conversion happens instantly in your browser. Since plain text files contain no timing
              data, the converter auto-generates sequential timestamps starting from 00:00:00. Each subtitle gets
              3 seconds of display time followed by a 0.5-second gap before the next entry appears.
            </p>
          </li>
          <li className="rounded-lg border bg-card p-5">
            <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-foreground text-background text-sm font-bold mb-3">3</span>
            <h3 className="font-semibold mb-1">Preview and Download SRT</h3>
            <p className="text-sm text-muted-foreground">
              Review the generated SRT output with numbered entries and timestamps. When satisfied, download the .srt
              file with a single click and import it into your video editor. You can fine-tune timing later using
              our{" "}
              <Link href="/tools/subtitle-shifter" className="font-medium underline underline-offset-4 hover:text-foreground/70">Subtitle Shifter</Link>.
            </p>
          </li>
        </ol>
      </section>

      <section className="pb-12">
        <h2 className="text-2xl font-bold mb-4">How Auto-Generated Timestamps Work</h2>
        <p className="text-sm text-muted-foreground leading-relaxed mb-4">
          The core challenge of converting TXT to SRT is that plain text files contain absolutely no timing
          information. A .txt file is just lines of text — there are no start times, end times, or duration markers.
          Our text to SRT converter solves this by assigning sequential timestamps based on a consistent default
          timing scheme that works well for most subtitle use cases.
        </p>
        <ul className="space-y-3 text-sm text-muted-foreground">
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0 w-44">Starting point:</span>
            The first subtitle entry always starts at 00:00:00,000. Every subsequent entry follows sequentially from where the previous one ended, plus a brief gap. This gives you a clean starting point that you can offset later if your video does not begin speaking immediately.
          </li>
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0 w-44">Display duration:</span>
            Each subtitle line receives exactly 3 seconds (3000 milliseconds) of on-screen display time. This 3-second default assumes approximately 15 words per subtitle line, which aligns with a comfortable reading speed for most viewers. Shorter lines will feel relaxed; longer lines may feel rushed.
          </li>
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0 w-44">Gap between entries:</span>
            A 0.5-second (500 millisecond) gap separates each subtitle entry. This brief pause gives viewers a visual break between consecutive subtitles, making it easier to notice when the text changes. Without this gap, back-to-back subtitles can feel continuous and hard to read.
          </li>
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0 w-44">Blank line handling:</span>
            Blank lines in your source file are skipped entirely during the conversion process. They do not create empty subtitle entries or affect timestamp calculations. This means you can use blank lines freely to organize sections of your script without impacting the output.
          </li>
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0 w-44">Reading speed math:</span>
            The 3-second-per-line default is based on subtitle industry guidelines. At an average reading speed of 150 to 180 words per minute, viewers can comfortably read about 12 to 15 words in 3 seconds. If your lines are significantly longer, consider splitting them before converting TXT to SRT for a better viewing experience.
          </li>
        </ul>
      </section>

      <section className="pb-12">
        <h2 className="text-2xl font-bold mb-4">Common Use Cases for TXT to SRT Conversion</h2>
        <ul className="space-y-3 text-sm text-muted-foreground">
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0">Transcripts to subtitles:</span>
            The most common workflow starts with a speech-to-text transcription tool that outputs plain text. You then run that transcript through this converter to generate a subtitle file, and finally import the SRT into your video editor for manual timing adjustments. This is far faster than creating subtitles from scratch inside an editor.
          </li>
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0">Song lyrics for music videos:</span>
            Convert lyrics from a plain text file into SRT subtitles for karaoke-style music videos or lyric videos. Each line of lyrics becomes a separate subtitle entry. After conversion, adjust the timing in your editor to match the actual song tempo and phrasing.
          </li>
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0">Script-based video production:</span>
            If you write video scripts in a text editor or word processor, save as .txt and convert it to subtitle format to generate a draft that follows your script structure. This is especially useful for educational content, tutorials, and explainer videos where the narration closely matches a written script.
          </li>
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0">Video editing import:</span>
            Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro, CapCut, and virtually all professional video editing software accept SRT files for subtitle tracks. Converting your plain text first is the standard way to get dialogue into these editors as timed subtitles.
          </li>
          <li className="flex gap-3">
            <span className="font-medium text-foreground shrink-0">Accessibility compliance:</span>
            Adding subtitles to video content is increasingly required for accessibility and legal compliance. If you have a written transcript but no subtitle file, converting that plain text into SRT format is the fastest path to generating closed captions for your content.
          </li>
        </ul>
      </section>

      <section className="pb-12">
        <h2 className="text-2xl font-bold mb-4">TXT vs SRT — What Makes Them Different</h2>
        <p className="text-sm text-muted-foreground leading-relaxed mb-4">
          Understanding the difference between TXT and SRT formats clarifies why you need a converter in the first
          place. A plain .txt file contains only raw text with no structural information — no timestamps, no entry
          numbers, no formatting metadata. An .srt file, on the other hand, is a structured subtitle format where
          each entry has a sequential index number, a start and end timestamp in HH:MM:SS,mmm format, and the
          subtitle text itself. When you convert TXT to SRT, the converter must generate all of this missing
          structure. That is what makes this conversion fundamentally different from format-to-format
          conversions like VTT to SRT or ASS to SRT, where timing already exists and only needs reformatting.
        </p>
      </section>

      {/* ===== Zone 3: FAQ + Related Tools ===== */}
      <section className="pb-12">
        <h2 className="text-2xl font-bold mb-4">Frequently Asked Questions</h2>
        <Accordion className="w-full">
          <AccordionItem value="timestamps">
            <AccordionTrigger>How are the timestamps generated when converting TXT to SRT?</AccordionTrigger>
            <AccordionContent>
              Since TXT files have no timing information, the converter auto-generates timestamps starting at
              00:00:00,000. Each non-empty line receives 3 seconds of display time with a 0.5-second gap between
              entries. For example, the first subtitle runs from 00:00:00,000 to 00:00:03,000, the second from
              00:00:03,500 to 00:00:06,500, and so on. This default timing assumes approximately 15 words per
              subtitle line, which matches a comfortable reading speed for most audiences.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="adjust-timing">
            <AccordionTrigger>Can I adjust the timing after converting text to SRT?</AccordionTrigger>
            <AccordionContent>
              Yes. The auto-generated timestamps are a starting point, not a final result. After converting your
              TXT to SRT, use our{" "}
              <Link href="/tools/subtitle-shifter" className="font-medium underline underline-offset-4 hover:text-foreground/70">Subtitle Shifter</Link>{" "}
              to offset all timestamps forward or backward by any amount. For per-line timing adjustments, import
              the SRT file into a subtitle editor or video editing software like Premiere Pro or DaVinci Resolve,
              where you can drag individual subtitle entries along the timeline.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="blank-lines">
            <AccordionTrigger>What happens to blank lines in my text file?</AccordionTrigger>
            <AccordionContent>
              Blank lines in the source file are skipped during the conversion. Only non-empty lines
              become subtitle entries with assigned timestamps. This means you can freely use blank lines to
              separate sections, paragraphs, or scenes in your script without creating empty subtitle entries in
              the output SRT file.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="privacy">
            <AccordionTrigger>Is my text file safe and private?</AccordionTrigger>
            <AccordionContent>
              Absolutely. All conversion processing happens directly in your web browser using client-side
              JavaScript. Your text file is never uploaded to any server, never transmitted over the internet, and
              never stored anywhere. We have zero access to your content. This makes our converter the most private
              option available for turning plain text into subtitles.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="languages">
            <AccordionTrigger>Does the TXT to SRT converter support non-English text?</AccordionTrigger>
            <AccordionContent>
              Yes. The converter handles UTF-8 encoded text, which means it supports all languages and writing
              systems including Chinese, Japanese, Korean, Arabic, Hebrew, Cyrillic, Thai, and all European
              languages. Character encoding is preserved exactly during the conversion process.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="video-editors">
            <AccordionTrigger>Which video editors accept SRT files generated from TXT?</AccordionTrigger>
            <AccordionContent>
              All major video editing software accepts standard SRT files, including Adobe Premiere Pro, DaVinci
              Resolve, Final Cut Pro, CapCut, iMovie, Avid Media Composer, and Vegas Pro. The SRT files generated
              by our TXT to SRT converter follow the standard SRT specification, so they are fully compatible with
              any application that supports SRT import.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="lyrics">
            <AccordionTrigger>Can I convert song lyrics from TXT to SRT for a music video?</AccordionTrigger>
            <AccordionContent>
              Yes, converting lyrics from TXT to SRT is one of the most popular use cases. Each line of your lyrics
              file becomes a separate subtitle entry with a 3-second duration. After conversion, you will likely
              need to adjust the timing in your video editor to sync each lyric line with the actual song tempo
              and vocal phrasing. Start by using the Subtitle Shifter to offset the entire file if the singing
              does not begin at the start of the video.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </section>

      <section className="pb-16">
        <h2 className="text-lg font-semibold mb-4">Related Subtitle Tools</h2>
        <div className="flex flex-wrap gap-2">
          {relatedTools.map((t) => (
            <Link key={t.href} href={t.href} className="inline-flex items-center rounded-lg border bg-card px-4 py-2 text-sm hover:bg-accent transition-colors">
              {t.name}
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}
