/**
 * SRT to ASS (Advanced SubStation Alpha) converter.
 *
 * Generates a valid ASS file with default styling from SRT entries.
 */

interface SrtEntry {
  start: string;
  end: string;
  text: string;
}

function parseSrt(content: string): SrtEntry[] {
  const blocks = content
    .replace(/\r\n/g, "\n")
    .trim()
    .split(/\n\s*\n/)
    .filter(Boolean);

  return blocks
    .map((block) => {
      const lines = block.split("\n");
      // Find the timestamp line
      const tsIdx = lines.findIndex((l) => l.includes("-->"));
      if (tsIdx < 0) return null;

      const tsParts = lines[tsIdx].split("-->");
      if (tsParts.length !== 2) return null;

      const start = tsParts[0].trim();
      const end = tsParts[1].trim();
      const text = lines
        .slice(tsIdx + 1)
        .join("\n")
        .trim();

      if (!text) return null;
      return { start, end, text };
    })
    .filter((e): e is SrtEntry => e !== null);
}

function srtTimestampToAss(ts: string): string {
  // SRT: HH:MM:SS,mmm → ASS: H:MM:SS.cc
  // Convert to total centiseconds first so rounding (e.g. 999 ms → 100 cs)
  // carries cleanly into the next second instead of producing invalid ".100".
  const match = ts.match(/(\d{2}):(\d{2}):(\d{2}),(\d{3})/);
  if (!match) return ts;

  const totalMs =
    parseInt(match[1], 10) * 3_600_000 +
    parseInt(match[2], 10) * 60_000 +
    parseInt(match[3], 10) * 1_000 +
    parseInt(match[4], 10);
  const totalCs = Math.round(totalMs / 10);

  const h = Math.floor(totalCs / 360_000); // no leading zero in ASS
  const mm = String(Math.floor((totalCs % 360_000) / 6_000)).padStart(2, "0");
  const ss = String(Math.floor((totalCs % 6_000) / 100)).padStart(2, "0");
  const cs = String(totalCs % 100).padStart(2, "0");

  return `${h}:${mm}:${ss}.${cs}`;
}

function stripBasicTags(text: string): string {
  return text.replace(/<\/?[biuBIU]>/g, "").replace(/\n/g, "\\N");
}

export function convertSrtToAss(content: string): string {
  const entries = parseSrt(content);

  const header = `[Script Info]
; Script generated by SubtitleOps
Title: Converted Subtitle
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text`;

  const dialogues = entries
    .map((entry) => {
      const start = srtTimestampToAss(entry.start);
      const end = srtTimestampToAss(entry.end);
      const text = stripBasicTags(entry.text);
      return `Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`;
    })
    .join("\n");

  return `${header}\n${dialogues}\n`;
}
