/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ToolsVttToTxtRouteImport } from './routes/tools/vtt-to-txt'
import { Route as ToolsVttToSrtRouteImport } from './routes/tools/vtt-to-srt'
import { Route as ToolsTxtToSrtRouteImport } from './routes/tools/txt-to-srt'
import { Route as ToolsSubtitleShiftRouteImport } from './routes/tools/subtitle-shift'
import { Route as ToolsSubtitleFpsConverterRouteImport } from './routes/tools/subtitle-fps-converter'
import { Route as ToolsSrtToVttRouteImport } from './routes/tools/srt-to-vtt'
import { Route as ToolsSrtToTxtRouteImport } from './routes/tools/srt-to-txt'
import { Route as ToolsSrtToAssRouteImport } from './routes/tools/srt-to-ass'
import { Route as ToolsSbvToSrtRouteImport } from './routes/tools/sbv-to-srt'
import { Route as ToolsAssToSrtRouteImport } from './routes/tools/ass-to-srt'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPaymentRouteImport } from './routes/settings/payment'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsFilesRouteImport } from './routes/settings/files'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as DashboardWorkflowsRouteImport } from './routes/dashboard/workflows'
import { Route as DashboardInviteRouteImport } from './routes/dashboard/invite'
import { Route as BlogWhatIsVttFileRouteImport } from './routes/blog/what-is-vtt-file'
import { Route as BlogWhatIsSrtFileRouteImport } from './routes/blog/what-is-srt-file'
import { Route as BlogWhatIsAssSubtitleFileRouteImport } from './routes/blog/what-is-ass-subtitle-file'
import { Route as BlogSrtVsVttWhichSubtitleFormatRouteImport } from './routes/blog/srt-vs-vtt-which-subtitle-format'
import { Route as BlogHowToFixSubtitleDelayOnlineRouteImport } from './routes/blog/how-to-fix-subtitle-delay-online'
import { Route as BlogAssVsSrtWhenToConvertRouteImport } from './routes/blog/ass-vs-srt-when-to-convert'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as pagesPricingRouteImport } from './routes/(pages)/pricing'
import { Route as pagesContactRouteImport } from './routes/(pages)/contact'
import { Route as pagesAboutRouteImport } from './routes/(pages)/about'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksCreemRouteImport } from './routes/api/webhooks/creem'
import { Route as ApiV1ConvertRouteImport } from './routes/api/v1/convert'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiSeoAnalyticsRouteImport } from './routes/api/seo/analytics'
import { Route as ApiE2eUsersRouteImport } from './routes/api/e2e/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsVttToTxtRoute = ToolsVttToTxtRouteImport.update({
  id: '/tools/vtt-to-txt',
  path: '/tools/vtt-to-txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVttToSrtRoute = ToolsVttToSrtRouteImport.update({
  id: '/tools/vtt-to-srt',
  path: '/tools/vtt-to-srt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTxtToSrtRoute = ToolsTxtToSrtRouteImport.update({
  id: '/tools/txt-to-srt',
  path: '/tools/txt-to-srt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSubtitleShiftRoute = ToolsSubtitleShiftRouteImport.update({
  id: '/tools/subtitle-shift',
  path: '/tools/subtitle-shift',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSubtitleFpsConverterRoute =
  ToolsSubtitleFpsConverterRouteImport.update({
    id: '/tools/subtitle-fps-converter',
    path: '/tools/subtitle-fps-converter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsSrtToVttRoute = ToolsSrtToVttRouteImport.update({
  id: '/tools/srt-to-vtt',
  path: '/tools/srt-to-vtt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSrtToTxtRoute = ToolsSrtToTxtRouteImport.update({
  id: '/tools/srt-to-txt',
  path: '/tools/srt-to-txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSrtToAssRoute = ToolsSrtToAssRouteImport.update({
  id: '/tools/srt-to-ass',
  path: '/tools/srt-to-ass',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSbvToSrtRoute = ToolsSbvToSrtRouteImport.update({
  id: '/tools/sbv-to-srt',
  path: '/tools/sbv-to-srt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAssToSrtRoute = ToolsAssToSrtRouteImport.update({
  id: '/tools/ass-to-srt',
  path: '/tools/ass-to-srt',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardWorkflowsRoute = DashboardWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInviteRoute = DashboardInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogWhatIsVttFileRoute = BlogWhatIsVttFileRouteImport.update({
  id: '/blog/what-is-vtt-file',
  path: '/blog/what-is-vtt-file',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhatIsSrtFileRoute = BlogWhatIsSrtFileRouteImport.update({
  id: '/blog/what-is-srt-file',
  path: '/blog/what-is-srt-file',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhatIsAssSubtitleFileRoute =
  BlogWhatIsAssSubtitleFileRouteImport.update({
    id: '/blog/what-is-ass-subtitle-file',
    path: '/blog/what-is-ass-subtitle-file',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSrtVsVttWhichSubtitleFormatRoute =
  BlogSrtVsVttWhichSubtitleFormatRouteImport.update({
    id: '/blog/srt-vs-vtt-which-subtitle-format',
    path: '/blog/srt-vs-vtt-which-subtitle-format',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToFixSubtitleDelayOnlineRoute =
  BlogHowToFixSubtitleDelayOnlineRouteImport.update({
    id: '/blog/how-to-fix-subtitle-delay-online',
    path: '/blog/how-to-fix-subtitle-delay-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAssVsSrtWhenToConvertRoute =
  BlogAssVsSrtWhenToConvertRouteImport.update({
    id: '/blog/ass-vs-srt-when-to-convert',
    path: '/blog/ass-vs-srt-when-to-convert',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const pagesPricingRoute = pagesPricingRouteImport.update({
  id: '/(pages)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesContactRoute = pagesContactRouteImport.update({
  id: '/(pages)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAboutRoute = pagesAboutRouteImport.update({
  id: '/(pages)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCreemRoute = ApiWebhooksCreemRouteImport.update({
  id: '/api/webhooks/creem',
  path: '/api/webhooks/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConvertRoute = ApiV1ConvertRouteImport.update({
  id: '/api/v1/convert',
  path: '/api/v1/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoAnalyticsRoute = ApiSeoAnalyticsRouteImport.update({
  id: '/api/seo/analytics',
  path: '/api/seo/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eUsersRoute = ApiE2eUsersRouteImport.update({
  id: '/api/e2e/users',
  path: '/api/e2e/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/ass-vs-srt-when-to-convert': typeof BlogAssVsSrtWhenToConvertRoute
  '/blog/how-to-fix-subtitle-delay-online': typeof BlogHowToFixSubtitleDelayOnlineRoute
  '/blog/srt-vs-vtt-which-subtitle-format': typeof BlogSrtVsVttWhichSubtitleFormatRoute
  '/blog/what-is-ass-subtitle-file': typeof BlogWhatIsAssSubtitleFileRoute
  '/blog/what-is-srt-file': typeof BlogWhatIsSrtFileRoute
  '/blog/what-is-vtt-file': typeof BlogWhatIsVttFileRoute
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/ass-to-srt': typeof ToolsAssToSrtRoute
  '/tools/sbv-to-srt': typeof ToolsSbvToSrtRoute
  '/tools/srt-to-ass': typeof ToolsSrtToAssRoute
  '/tools/srt-to-txt': typeof ToolsSrtToTxtRoute
  '/tools/srt-to-vtt': typeof ToolsSrtToVttRoute
  '/tools/subtitle-fps-converter': typeof ToolsSubtitleFpsConverterRoute
  '/tools/subtitle-shift': typeof ToolsSubtitleShiftRoute
  '/tools/txt-to-srt': typeof ToolsTxtToSrtRoute
  '/tools/vtt-to-srt': typeof ToolsVttToSrtRoute
  '/tools/vtt-to-txt': typeof ToolsVttToTxtRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/seo/analytics': typeof ApiSeoAnalyticsRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/v1/convert': typeof ApiV1ConvertRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/ass-vs-srt-when-to-convert': typeof BlogAssVsSrtWhenToConvertRoute
  '/blog/how-to-fix-subtitle-delay-online': typeof BlogHowToFixSubtitleDelayOnlineRoute
  '/blog/srt-vs-vtt-which-subtitle-format': typeof BlogSrtVsVttWhichSubtitleFormatRoute
  '/blog/what-is-ass-subtitle-file': typeof BlogWhatIsAssSubtitleFileRoute
  '/blog/what-is-srt-file': typeof BlogWhatIsSrtFileRoute
  '/blog/what-is-vtt-file': typeof BlogWhatIsVttFileRoute
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/ass-to-srt': typeof ToolsAssToSrtRoute
  '/tools/sbv-to-srt': typeof ToolsSbvToSrtRoute
  '/tools/srt-to-ass': typeof ToolsSrtToAssRoute
  '/tools/srt-to-txt': typeof ToolsSrtToTxtRoute
  '/tools/srt-to-vtt': typeof ToolsSrtToVttRoute
  '/tools/subtitle-fps-converter': typeof ToolsSubtitleFpsConverterRoute
  '/tools/subtitle-shift': typeof ToolsSubtitleShiftRoute
  '/tools/txt-to-srt': typeof ToolsTxtToSrtRoute
  '/tools/vtt-to-srt': typeof ToolsVttToSrtRoute
  '/tools/vtt-to-txt': typeof ToolsVttToTxtRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/seo/analytics': typeof ApiSeoAnalyticsRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/v1/convert': typeof ApiV1ConvertRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/(pages)/about': typeof pagesAboutRoute
  '/(pages)/contact': typeof pagesContactRoute
  '/(pages)/pricing': typeof pagesPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/ass-vs-srt-when-to-convert': typeof BlogAssVsSrtWhenToConvertRoute
  '/blog/how-to-fix-subtitle-delay-online': typeof BlogHowToFixSubtitleDelayOnlineRoute
  '/blog/srt-vs-vtt-which-subtitle-format': typeof BlogSrtVsVttWhichSubtitleFormatRoute
  '/blog/what-is-ass-subtitle-file': typeof BlogWhatIsAssSubtitleFileRoute
  '/blog/what-is-srt-file': typeof BlogWhatIsSrtFileRoute
  '/blog/what-is-vtt-file': typeof BlogWhatIsVttFileRoute
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/ass-to-srt': typeof ToolsAssToSrtRoute
  '/tools/sbv-to-srt': typeof ToolsSbvToSrtRoute
  '/tools/srt-to-ass': typeof ToolsSrtToAssRoute
  '/tools/srt-to-txt': typeof ToolsSrtToTxtRoute
  '/tools/srt-to-vtt': typeof ToolsSrtToVttRoute
  '/tools/subtitle-fps-converter': typeof ToolsSubtitleFpsConverterRoute
  '/tools/subtitle-shift': typeof ToolsSubtitleShiftRoute
  '/tools/txt-to-srt': typeof ToolsTxtToSrtRoute
  '/tools/vtt-to-srt': typeof ToolsVttToSrtRoute
  '/tools/vtt-to-txt': typeof ToolsVttToTxtRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/seo/analytics': typeof ApiSeoAnalyticsRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/v1/convert': typeof ApiV1ConvertRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/ass-vs-srt-when-to-convert'
    | '/blog/how-to-fix-subtitle-delay-online'
    | '/blog/srt-vs-vtt-which-subtitle-format'
    | '/blog/what-is-ass-subtitle-file'
    | '/blog/what-is-srt-file'
    | '/blog/what-is-vtt-file'
    | '/dashboard/invite'
    | '/dashboard/workflows'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/ass-to-srt'
    | '/tools/sbv-to-srt'
    | '/tools/srt-to-ass'
    | '/tools/srt-to-txt'
    | '/tools/srt-to-vtt'
    | '/tools/subtitle-fps-converter'
    | '/tools/subtitle-shift'
    | '/tools/txt-to-srt'
    | '/tools/vtt-to-srt'
    | '/tools/vtt-to-txt'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/settings/'
    | '/tools/'
    | '/api/auth/$'
    | '/api/e2e/users'
    | '/api/seo/analytics'
    | '/api/storage/file'
    | '/api/v1/convert'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manifest.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/ass-vs-srt-when-to-convert'
    | '/blog/how-to-fix-subtitle-delay-online'
    | '/blog/srt-vs-vtt-which-subtitle-format'
    | '/blog/what-is-ass-subtitle-file'
    | '/blog/what-is-srt-file'
    | '/blog/what-is-vtt-file'
    | '/dashboard/invite'
    | '/dashboard/workflows'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/ass-to-srt'
    | '/tools/sbv-to-srt'
    | '/tools/srt-to-ass'
    | '/tools/srt-to-txt'
    | '/tools/srt-to-vtt'
    | '/tools/subtitle-fps-converter'
    | '/tools/subtitle-shift'
    | '/tools/txt-to-srt'
    | '/tools/vtt-to-srt'
    | '/tools/vtt-to-txt'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/settings'
    | '/tools'
    | '/api/auth/$'
    | '/api/e2e/users'
    | '/api/seo/analytics'
    | '/api/storage/file'
    | '/api/v1/convert'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/(pages)/about'
    | '/(pages)/contact'
    | '/(pages)/pricing'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/ass-vs-srt-when-to-convert'
    | '/blog/how-to-fix-subtitle-delay-online'
    | '/blog/srt-vs-vtt-which-subtitle-format'
    | '/blog/what-is-ass-subtitle-file'
    | '/blog/what-is-srt-file'
    | '/blog/what-is-vtt-file'
    | '/dashboard/invite'
    | '/dashboard/workflows'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/ass-to-srt'
    | '/tools/sbv-to-srt'
    | '/tools/srt-to-ass'
    | '/tools/srt-to-txt'
    | '/tools/srt-to-vtt'
    | '/tools/subtitle-fps-converter'
    | '/tools/subtitle-shift'
    | '/tools/txt-to-srt'
    | '/tools/vtt-to-srt'
    | '/tools/vtt-to-txt'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/settings/'
    | '/tools/'
    | '/api/auth/$'
    | '/api/e2e/users'
    | '/api/seo/analytics'
    | '/api/storage/file'
    | '/api/v1/convert'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  pagesAboutRoute: typeof pagesAboutRoute
  pagesContactRoute: typeof pagesContactRoute
  pagesPricingRoute: typeof pagesPricingRoute
  ApiPingRoute: typeof ApiPingRoute
  BlogAssVsSrtWhenToConvertRoute: typeof BlogAssVsSrtWhenToConvertRoute
  BlogHowToFixSubtitleDelayOnlineRoute: typeof BlogHowToFixSubtitleDelayOnlineRoute
  BlogSrtVsVttWhichSubtitleFormatRoute: typeof BlogSrtVsVttWhichSubtitleFormatRoute
  BlogWhatIsAssSubtitleFileRoute: typeof BlogWhatIsAssSubtitleFileRoute
  BlogWhatIsSrtFileRoute: typeof BlogWhatIsSrtFileRoute
  BlogWhatIsVttFileRoute: typeof BlogWhatIsVttFileRoute
  ToolsAssToSrtRoute: typeof ToolsAssToSrtRoute
  ToolsSbvToSrtRoute: typeof ToolsSbvToSrtRoute
  ToolsSrtToAssRoute: typeof ToolsSrtToAssRoute
  ToolsSrtToTxtRoute: typeof ToolsSrtToTxtRoute
  ToolsSrtToVttRoute: typeof ToolsSrtToVttRoute
  ToolsSubtitleFpsConverterRoute: typeof ToolsSubtitleFpsConverterRoute
  ToolsSubtitleShiftRoute: typeof ToolsSubtitleShiftRoute
  ToolsTxtToSrtRoute: typeof ToolsTxtToSrtRoute
  ToolsVttToSrtRoute: typeof ToolsVttToSrtRoute
  ToolsVttToTxtRoute: typeof ToolsVttToTxtRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiE2eUsersRoute: typeof ApiE2eUsersRoute
  ApiSeoAnalyticsRoute: typeof ApiSeoAnalyticsRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiV1ConvertRoute: typeof ApiV1ConvertRoute
  ApiWebhooksCreemRoute: typeof ApiWebhooksCreemRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/vtt-to-txt': {
      id: '/tools/vtt-to-txt'
      path: '/tools/vtt-to-txt'
      fullPath: '/tools/vtt-to-txt'
      preLoaderRoute: typeof ToolsVttToTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/vtt-to-srt': {
      id: '/tools/vtt-to-srt'
      path: '/tools/vtt-to-srt'
      fullPath: '/tools/vtt-to-srt'
      preLoaderRoute: typeof ToolsVttToSrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/txt-to-srt': {
      id: '/tools/txt-to-srt'
      path: '/tools/txt-to-srt'
      fullPath: '/tools/txt-to-srt'
      preLoaderRoute: typeof ToolsTxtToSrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/subtitle-shift': {
      id: '/tools/subtitle-shift'
      path: '/tools/subtitle-shift'
      fullPath: '/tools/subtitle-shift'
      preLoaderRoute: typeof ToolsSubtitleShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/subtitle-fps-converter': {
      id: '/tools/subtitle-fps-converter'
      path: '/tools/subtitle-fps-converter'
      fullPath: '/tools/subtitle-fps-converter'
      preLoaderRoute: typeof ToolsSubtitleFpsConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/srt-to-vtt': {
      id: '/tools/srt-to-vtt'
      path: '/tools/srt-to-vtt'
      fullPath: '/tools/srt-to-vtt'
      preLoaderRoute: typeof ToolsSrtToVttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/srt-to-txt': {
      id: '/tools/srt-to-txt'
      path: '/tools/srt-to-txt'
      fullPath: '/tools/srt-to-txt'
      preLoaderRoute: typeof ToolsSrtToTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/srt-to-ass': {
      id: '/tools/srt-to-ass'
      path: '/tools/srt-to-ass'
      fullPath: '/tools/srt-to-ass'
      preLoaderRoute: typeof ToolsSrtToAssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sbv-to-srt': {
      id: '/tools/sbv-to-srt'
      path: '/tools/sbv-to-srt'
      fullPath: '/tools/sbv-to-srt'
      preLoaderRoute: typeof ToolsSbvToSrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ass-to-srt': {
      id: '/tools/ass-to-srt'
      path: '/tools/ass-to-srt'
      fullPath: '/tools/ass-to-srt'
      preLoaderRoute: typeof ToolsAssToSrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/workflows': {
      id: '/dashboard/workflows'
      path: '/workflows'
      fullPath: '/dashboard/workflows'
      preLoaderRoute: typeof DashboardWorkflowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invite': {
      id: '/dashboard/invite'
      path: '/invite'
      fullPath: '/dashboard/invite'
      preLoaderRoute: typeof DashboardInviteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/what-is-vtt-file': {
      id: '/blog/what-is-vtt-file'
      path: '/blog/what-is-vtt-file'
      fullPath: '/blog/what-is-vtt-file'
      preLoaderRoute: typeof BlogWhatIsVttFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-srt-file': {
      id: '/blog/what-is-srt-file'
      path: '/blog/what-is-srt-file'
      fullPath: '/blog/what-is-srt-file'
      preLoaderRoute: typeof BlogWhatIsSrtFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-ass-subtitle-file': {
      id: '/blog/what-is-ass-subtitle-file'
      path: '/blog/what-is-ass-subtitle-file'
      fullPath: '/blog/what-is-ass-subtitle-file'
      preLoaderRoute: typeof BlogWhatIsAssSubtitleFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/srt-vs-vtt-which-subtitle-format': {
      id: '/blog/srt-vs-vtt-which-subtitle-format'
      path: '/blog/srt-vs-vtt-which-subtitle-format'
      fullPath: '/blog/srt-vs-vtt-which-subtitle-format'
      preLoaderRoute: typeof BlogSrtVsVttWhichSubtitleFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-fix-subtitle-delay-online': {
      id: '/blog/how-to-fix-subtitle-delay-online'
      path: '/blog/how-to-fix-subtitle-delay-online'
      fullPath: '/blog/how-to-fix-subtitle-delay-online'
      preLoaderRoute: typeof BlogHowToFixSubtitleDelayOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ass-vs-srt-when-to-convert': {
      id: '/blog/ass-vs-srt-when-to-convert'
      path: '/blog/ass-vs-srt-when-to-convert'
      fullPath: '/blog/ass-vs-srt-when-to-convert'
      preLoaderRoute: typeof BlogAssVsSrtWhenToConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(pages)/pricing': {
      id: '/(pages)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof pagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/contact': {
      id: '/(pages)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof pagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/about': {
      id: '/(pages)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof pagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/creem': {
      id: '/api/webhooks/creem'
      path: '/api/webhooks/creem'
      fullPath: '/api/webhooks/creem'
      preLoaderRoute: typeof ApiWebhooksCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/convert': {
      id: '/api/v1/convert'
      path: '/api/v1/convert'
      fullPath: '/api/v1/convert'
      preLoaderRoute: typeof ApiV1ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/analytics': {
      id: '/api/seo/analytics'
      path: '/api/seo/analytics'
      fullPath: '/api/seo/analytics'
      preLoaderRoute: typeof ApiSeoAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/users': {
      id: '/api/e2e/users'
      path: '/api/e2e/users'
      fullPath: '/api/e2e/users'
      preLoaderRoute: typeof ApiE2eUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardInviteRoute: typeof DashboardInviteRoute
  DashboardWorkflowsRoute: typeof DashboardWorkflowsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInviteRoute: DashboardInviteRoute,
  DashboardWorkflowsRoute: DashboardWorkflowsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  pagesAboutRoute: pagesAboutRoute,
  pagesContactRoute: pagesContactRoute,
  pagesPricingRoute: pagesPricingRoute,
  ApiPingRoute: ApiPingRoute,
  BlogAssVsSrtWhenToConvertRoute: BlogAssVsSrtWhenToConvertRoute,
  BlogHowToFixSubtitleDelayOnlineRoute: BlogHowToFixSubtitleDelayOnlineRoute,
  BlogSrtVsVttWhichSubtitleFormatRoute: BlogSrtVsVttWhichSubtitleFormatRoute,
  BlogWhatIsAssSubtitleFileRoute: BlogWhatIsAssSubtitleFileRoute,
  BlogWhatIsSrtFileRoute: BlogWhatIsSrtFileRoute,
  BlogWhatIsVttFileRoute: BlogWhatIsVttFileRoute,
  ToolsAssToSrtRoute: ToolsAssToSrtRoute,
  ToolsSbvToSrtRoute: ToolsSbvToSrtRoute,
  ToolsSrtToAssRoute: ToolsSrtToAssRoute,
  ToolsSrtToTxtRoute: ToolsSrtToTxtRoute,
  ToolsSrtToVttRoute: ToolsSrtToVttRoute,
  ToolsSubtitleFpsConverterRoute: ToolsSubtitleFpsConverterRoute,
  ToolsSubtitleShiftRoute: ToolsSubtitleShiftRoute,
  ToolsTxtToSrtRoute: ToolsTxtToSrtRoute,
  ToolsVttToSrtRoute: ToolsVttToSrtRoute,
  ToolsVttToTxtRoute: ToolsVttToTxtRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiE2eUsersRoute: ApiE2eUsersRoute,
  ApiSeoAnalyticsRoute: ApiSeoAnalyticsRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiV1ConvertRoute: ApiV1ConvertRoute,
  ApiWebhooksCreemRoute: ApiWebhooksCreemRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
